### ISSUE TITLE
Scala 2.13.0-M1 build, pls

### ISSUE THREAD

**Issue by golem131** [ensime/pcplod#22]

**Comment by SethTisue** [comment]
it would be helpful to have this published, because of this dependency chain:

pcplod <- kind-projector <- specs2 <- (big swathes of the ecosystem)

**Comment by fommil** [comment]
I'll have a look. Somehow one of the tests has started to fail.

**Comment by fommil** [comment]
no changes needed. I'll release today.

**Comment by fommil** [comment]
released

**Comment by SethTisue** [comment]
thanks Sam! I updated https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md
