### ISSUE TITLE
Implement all the things

### ISSUE THREAD

**Issue by fommil** [ensime/pcplod#3]

**Comment by hedefalk** [comment]
What happened to Imaginary friend?

**Comment by fommil** [comment]
it's still around :-) it might morph into an example rather than the library

**Comment by hedefalk** [comment]
But this is the same thing, right?

**Comment by fommil** [comment]
pretty much. it didn't make sense to call the testing library after the example... plus I never actually wrote it, I just did the example (I needed it for work).
